### PR TITLE
remove make test-integration call from deploy

### PR DESCRIPTION
**Pull request by desa**
*Note* Opened https://github.com/influxdata/platform/issues/1676 as a result of this https://github.com/influxdata/platform/pull/1672/commits/389d7eb813ef0645e0ae13943bd58a358c01f7a4

_What was the problem?_
Running `make test-integration` resulted in
```
...
?   	github.com/influxdata/platform/pkg/binaryutil	[no test files]
# github.com/docker/docker/client
../../../../pkg/mod/github.com/docker/docker@v0.0.0-20180422163414-57142e89befe/client/container_commit.go:17:15: undefined: reference.ParseNormalizedNamed
../../../../pkg/mod/github.com/docker/docker@v0.0.0-20180422163414-57142e89befe/client/container_commit.go:25:9: undefined: reference.TagNameOnly
../../../../pkg/mod/github.com/docker/docker@v0.0.0-20180422163414-57142e89befe/client/container_commit.go:30:16: undefined: reference.FamiliarName
../../../../pkg/mod/github.com/docker/docker@v0.0.0-20180422163414-57142e89befe/client/image_create.go:17:14: undefined: reference.ParseNormalizedNamed
../../../../pkg/mod/github.com/docker/docker@v0.0.0-20180422163414-57142e89befe/client/image_create.go:23:25: undefined: reference.FamiliarName
../../../../pkg/mod/github.com/docker/docker@v0.0.0-20180422163414-57142e89befe/client/image_import.go:19:16: undefined: reference.ParseNormalizedNamed
../../../../pkg/mod/github.com/docker/docker@v0.0.0-20180422163414-57142e89befe/client/image_pull.go:24:14: undefined: reference.ParseNormalizedNamed
../../../../pkg/mod/github.com/docker/docker@v0.0.0-20180422163414-57142e89befe/client/image_pull.go:30:25: undefined: reference.FamiliarName
../../../../pkg/mod/github.com/docker/docker@v0.0.0-20180422163414-57142e89befe/client/image_pull.go:60:8: undefined: reference.TagNameOnly
../../../../pkg/mod/github.com/docker/docker@v0.0.0-20180422163414-57142e89befe/client/image_push.go:20:14: undefined: reference.ParseNormalizedNamed
../../../../pkg/mod/github.com/docker/docker@v0.0.0-20180422163414-57142e89befe/client/image_push.go:20:14: too many errors
ok  	github.com/influxdata/platform/pkg/bloom	27.607s
...
```

_What was the solution?_
Use a different version of docker.

  - [ ] Rebased/mergeable
  - [ ] Tests pas

### CODE REVIEW

**Comment by desa** [comment]
@mark-rushakoff any thoughts on why the api compatibility tests aren't running? I have some concerns that this docker change might cause issues with idpe. Also any thoughts on how we should test things like this? Since we can't actually demonstrate that the issue at hand will be solved since `make test-integration` only runs for nightlies

@jademcgough I added a sort call to `FindLabels` in the inmem label service so that we can guarantee that the labels come back in a specific order. I was having some issues with some failing tests.

**Comment by desa** [comment]
>then make a commit that forces the integration tests to run, see that it passes, comment with a link to that build, then force-push away that change.

I really like this idea. Thanks.

**Comment by docmerlin** [comment]
`github.com/Sirupsen/logrus` is a problem
@mark-rushakoff 
@desa 
You can't use this one or any package that uses it, you have to use the lower case `github.com/sirupsen/logrus` everywhere.  MacOS will let you get away with both, but on linux you can't because the file system is case sensitive.

**Comment by desa** [comment]
Closing in favor of https://github.com/influxdata/platform/pull/1700

**Pull request closed without merging**
