### PR TITLE
feat(query/function): Add meta query helper functions

### LINKED ISSUE #85: Create helper functions for meta queries.
See https://gist.github.com/stuartcarnie/0e94582dc740ff3a032306d1829c0773

### PR DESCRIPTION
**Pull request by nathanielc**
Fixes #85

### CODE REVIEW

**Comment by desa** [comment]
@nathanielc is this PR mergable? If not would you mind closing it. We've built up a bit of PR cruft in platform and idpe.

**Comment by nathanielc** [comment]
This is blocked on https://github.com/influxdata/platform/issues/497 being fixed.

**Comment by jsternberg** [comment]
This likely needs to be moved to `influxdata/flux`.

**Comment by nathanielc** [comment]
Closing in favor of https://github.com/influxdata/flux/pull/225

**Pull request closed without merging**
