### PR TITLE
Do for in-mem tasks

### PR DESCRIPTION
**Pull request by docmerlin**
This adds an Each method to the inmem task store so we can handle user and org deletions more easily in the enterprise version.

### CODE REVIEW

**Comment by mark-rushakoff** [comment]
If this is for testing, what tests are going to use `Do`?

**Comment by lyondhill** [comment]
I think im with mark. What value does this add or what problem does it fix?

**Comment by docmerlin** [comment]
@mark-rushakoff @lyondhill this is for deletion of orgs and groups in Enterprise.

**Comment by docmerlin** [comment]
Closing this.

**Pull request closed without merging**
