### PR TITLE
fix(http): Update members/owners endpoints to implement swagger definitions

### LINKED ISSUE #1417: GET /api/v2/orgs/:org_id:/members should return an org's members
According to the [spec][0], `GET /api/v2/orgs/:org_id:/members` should return something like:

```
{
  "links": {
    "self": "string"
  },
  "users": [
    {
      "user": {
        "id": "string",
        "name": "string",
        "status": "active"
      },
      "links": {
        "self": "string"
      }
    }
  ]
}
```

It currently returns
```
{
  "userResourceMappings": []
}
```

[0]: https://github.com/influxdata/platform/blob/81c0e53c4a515668db7181b01f832d852f521109/http/swagger.yml#L2293-L2318

### PR DESCRIPTION
**Pull request by zhulongcheng**
Closes #1417 #1410 #1921

  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] swagger.json updated (if modified Go structs or API)

### CODE REVIEW

**Comment by zhulongcheng** [comment]
@goller @kelwang @jademcgough  Request reviews. Thanks!    ❤️  😂

**Comment by goller** [comment]
@zhulongcheng I'd like to get all this amazing work merged in today.  Do you mind rebasing?

**Comment by goller** [comment]
This would close #1921

**Comment by zhulongcheng** [comment]
@goller rebased.

**Comment by jademcgough** [comment]
This looks great, thank you!

**Comment by bednar** [comment]
Hi @zhulongcheng, @jademcgough 

I have a small issue with this PR. The adding member or owner for bucket and organization does not work by HTTP endpoins "/api/v2/buckets/" and "/api/v2/orgs/". 

The request is **timed out** and user is not added.

The reason is that the **UserService** is not defined: [bucket_service.go](https://github.com/influxdata/platform/blob/107431523e29546e32de68abb57de5c0128b7f77/http/bucket_service.go#L56) -> [user_resource_mapping_service.go](https://github.com/influxdata/platform/blob/107431523e29546e32de68abb57de5c0128b7f77/http/user_resource_mapping_service.go#L56) is not defined.

### Add member to bucket
```
curl -i -m 10 -X POST http://127.0.0.1:9999/api/v2/buckets/031ac7205945c000/members -H 'accept: application/json' \
    -H 'Authorization: Token 9Qi7cSLrgS1FUyFOMXNu69LCPqgmcNcMvTWnwMGt0qRNkMOjj8auGnkgGsyk4CtPBQEbFHSM2K5y3OkToGF_Rw==' \
    -d '{"id":"031ac7206305c000"}'

curl: (28) Operation timed out after 10004 milliseconds with 0 bytes received
```

**Comment by jademcgough** [comment]
@bednar I'm taking a look.

**Pull request merged**
