### PR TITLE
Make chronograf directory for js code only

### PR DESCRIPTION
**Pull request by desa**
_Briefly describe your proposed changes:_
Previously the chronograf code base contained both the Go and JS code. This PR moves the Go code into a directory called `v1` and the js code into the chronograf directory

  - [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] swagger.json updated (if modified Go structs or API)
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by desa** [comment]
Huh I'm surprised the switch is being tracked as additions because I did a `git mv`

**Comment by chnn** [comment]
This will be rad. I'm having trouble building though. After a `make clean` and then `make` in the platform root, I get
```
make[1]: *** No rule to make target `ui/node_modules/fileset/test/fixtures/an', needed by `build'.  Stop.
make: *** [chronograf] Error 2
```

**Comment by desa** [comment]
@chnn super weird. Lets sync up today and see if we can figure out whats happening. There should be no relevant references to the `ui` directory in the makefile.

**Comment by chnn** [comment]
@desa sounds good, I'm free whenever for a quick call

**Comment by 121watts** [comment]
merge away once ✅

**Pull request merged**
